services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    container_name: postgres
    volumes:
      - /postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
