services:
  blogapp:
    image: blogapp-frontend-dev
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile
    container_name: blogapp-frontend-dev

  
  server:
    image: blogapp-backend-dev
    build:
      context: ./backend
      dockerfile: dev.Dockerfile
    container_name: blogapp-backend-dev
    environment:
      - PORT=3003
      - MONGODB_URL=mongodb+srv://fullstack:XXXXXXXXXXXXXXXXXXXXXXXX@cluster0.wctwxl0.mongodb.net/Blogs?retryWrites=true&w=majority
      - SECRET=YYYYYYYYYYYY

  nginx:
    image: nginx
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
      - 3000:80
    container_name: reverse-proxy
    depends_on:
      - blogapp
      - server
